force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Customer Account</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/ApplicationCircuit__c.field-meta.xml
<CustomField>
    <fullName>ApplicationCircuit__c</fullName>
    <businessOwnerUser>mikew@welco.ca.traintest</businessOwnerUser>
    <description>Describes the location or circuit the equipment is in within the facility or plant as requested by MW</description>
    <inlineHelpText>Describe the location, application or circuit the equipment is in within the facility or plant.</inlineHelpText>
    <label>Application/Circuit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Category_Code__c.field-meta.xml
<CustomField>
    <fullName>Category_Code__c</fullName>
    <description>Tracks Opportunity Codes based off of Adagio System codes</description>
    <label>Category Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Supplier__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Category_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Source__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Source__c</fullName>
    <label>Opportunity Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Referral</fullName>
            </value>
            <value>
                <fullName>Digital Advertising</fullName>
            </value>
            <value>
                <fullName>Eriez Orange Room</fullName>
            </value>
            <value>
                <fullName>Existing Business</fullName>
            </value>
            <value>
                <fullName>Magazine/Publication</fullName>
            </value>
            <value>
                <fullName>Phone/Email/Site Visit (Account Manager)</fullName>
            </value>
            <value>
                <fullName>Phone/Email (Inside Sales)</fullName>
            </value>
            <value>
                <fullName>President/VP Referral</fullName>
            </value>
            <value>
                <fullName>Supplier Referral</fullName>
            </value>
            <value>
                <fullName>Trade Show/Event</fullName>
            </value>
            <value>
                <fullName>Welco Campaigns</fullName>
            </value>
            <value>
                <fullName>Welco Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <description>Identifies whether the opportunity is for units or parts</description>
    <inlineHelpText>Parts opportunities do not require kickoff meetings.</inlineHelpText>
    <label>Opportunity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Parts</fullName>
            </value>
            <value>
                <fullName>Units</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <businessOwnerUser>annat@welco.ca.traintest</businessOwnerUser>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used to lookup to Contacts to select the primary contact/person for this opportunity.</description>
    <inlineHelpText>Primary contact for this opportunity and who the quote will be addressed to. Don&apos;t worry, you will be able to add more later.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Contact of These Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Role__c</fullName>
    <description>Picklist allowing users to add the primary contact role for the opportunity</description>
    <label>Primary Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adversary</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>EPC</fullName>
            </value>
            <value>
                <fullName>Influencer</fullName>
            </value>
            <value>
                <fullName>Operator/Maintenance</fullName>
            </value>
            <value>
                <fullName>Planner</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Purchaser</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <description>Vendor Reference Code for this Opportunity</description>
    <label>Quote Reference</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <description>Used to identify if the sale type is regular or direct. Direct sales do not require kickoff meetings.</description>
    <inlineHelpText>Direct sales do not require kickoff meetings.</inlineHelpText>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <description>Tracks the supplier associated with this opportunity.</description>
    <label>Supplier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Supplier</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Placement__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Placement__c</fullName>
    <businessOwnerUser>accounting1@welco.ca.traintest</businessOwnerUser>
    <description>Based off of list from Krebs</description>
    <inlineHelpText>Existing (Spare/Stock/Rotatable) and Repair Replacement opportunities do not require kickoff meetings.</inlineHelpText>
    <label>Type of Placement</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Application</fullName>
            </value>
            <value>
                <fullName>Competitor Replacement</fullName>
            </value>
            <value>
                <fullName>Upgrade Existing</fullName>
            </value>
            <value>
                <fullName>Existing (Spare/Stock/Rotatable)</fullName>
            </value>
            <value>
                <fullName>Repair Replacement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Units</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Supplier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A.R. Thomson</fullName>
    </customValue>
    <customValue>
        <fullName>Aesseal Canada Inc.</fullName>
    </customValue>
    <customValue>
        <fullName>Albany Pump</fullName>
    </customValue>
    <customValue>
        <fullName>Allgaier</fullName>
    </customValue>
    <customValue>
        <fullName>BDI</fullName>
    </customValue>
    <customValue>
        <fullName>BJM Pumps</fullName>
    </customValue>
    <customValue>
        <fullName>Cleveland Vibrator</fullName>
    </customValue>
    <customValue>
        <fullName>CMI</fullName>
    </customValue>
    <customValue>
        <fullName>CSM Steel Fab</fullName>
    </customValue>
    <customValue>
        <fullName>CTI</fullName>
    </customValue>
    <customValue>
        <fullName>Cunningham</fullName>
    </customValue>
    <customValue>
        <fullName>Elgin Separation Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Eriez</fullName>
    </customValue>
    <customValue>
        <fullName>Flexicon</fullName>
    </customValue>
    <customValue>
        <fullName>FLSmidth Krebs</fullName>
    </customValue>
    <customValue>
        <fullName>FLSmidth PT</fullName>
    </customValue>
    <customValue>
        <fullName>FLSmidth SLC</fullName>
        <label>FLSmidth Salt Lake City</label>
    </customValue>
    <customValue>
        <fullName>HammerTek</fullName>
    </customValue>
    <customValue>
        <fullName>Hy-Tran</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial Flow Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Jadco</fullName>
    </customValue>
    <customValue>
        <fullName>Miller-Leaman</fullName>
    </customValue>
    <customValue>
        <fullName>Mody Pumps</fullName>
    </customValue>
    <customValue>
        <fullName>Motion Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Norris Screens</fullName>
    </customValue>
    <customValue>
        <fullName>Norwesco</fullName>
    </customValue>
    <customValue>
        <fullName>Nu-Clean</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Polaris Pumps</fullName>
    </customValue>
    <customValue>
        <fullName>Ruhrpumpen</fullName>
    </customValue>
    <masterLabel>Supplier</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RecentlyWonOpportunitiesTest.cls
@isTest
private class RecentlyWonOpportunitiesTest {
    @testSetup
    static void DataSetup() {
        //get last weeks date
        Date lastWeek = Date.Today() - 75;
        
        //Account and Contact creation for Opportunity required fields.
        Account acc = new Account();
        acc.Name = 'Burlington Textiles Corp of America';
        insert acc;
        
        Contact cont = new Contact();
		cont.FirstName='Test';
		cont.LastName='Test';
		cont.Accountid= acc.id;
		insert cont;
        
        //Opportunity that should be found by RecentlyWonOpportunities
        Opportunity correctOpp = new Opportunity(Name = 'TestingTrue',
                                                 Sale_Type__c = 'Regular',
                                                 StageName = 'Closed Won',
                                                 CloseDate = Date.today(),
                                                 Supplier__c = 'BDI',
                                                 Category_Code__c = 'AAA',
                                                 Opportunity_Type__c = 'Units',
                                                 Units__c = 1,
                                                 ApplicationCircuit__c = 'pump',
                                                 Type_of_Placement__c = 'New Application',
                                                 AccountId = acc.id,
                                                 Primary_Contact__c = cont.id,
                                                 Primary_Contact_Role__c = 'Contractor',
                                                 Opportunity_Source__c = 'Customer Referral',
                                                 Reference__c = '123',
                                                 Amount = 1000);
        insert correctOpp;   

        
        //Opportunity that should not be found by RecentlyWonOpportunities
        Opportunity incorrectOpp = new Opportunity(Name = 'TestingFalse',
                                                   Sale_Type__c='Regular',
                                                   StageName = 'Closed Lost',
        										   CloseDate = lastWeek,
                                                   Supplier__c = 'BDI',
                                                   Category_Code__c = 'AAA',
                                                   Opportunity_Type__c ='Units',
                                                   Units__c=1,
                                                   ApplicationCircuit__c='pumps',
                                                   Type_of_Placement__c='New Application',
                                                   AccountId = acc.id,
                                                   Primary_Contact__c = cont.id,
                                                   Primary_Contact_Role__c = 'Contractor',
                                                   Opportunity_Source__c = 'Customer Referral',
                                                   Reference__c = '123');
        insert incorrectOpp;
        
        incorrectOpp.CloseDate = lastWeek;
        update incorrectOpp;
        
        
        //Closed/Won but more than a few days out.
        Opportunity incorrectOpp2 = new Opportunity(Name = 'TestingFalseAgain',
                                                    Sale_Type__c = 'Regular',
                                                    StageName = 'Closed Won',
                                                    CloseDate = lastWeek,
                                                    Supplier__c = 'BDI',
        											Category_Code__c = 'AAA',
                                                    Opportunity_Type__c = 'Units',
                                                    Units__c = 1,
                                                    ApplicationCircuit__c = 'pump',
                                                    Type_of_Placement__c = 'New Application',
                                                    AccountId = acc.id,
                                                    Primary_Contact__c = cont.id,
                                                    Primary_Contact_Role__c = 'Contractor',
                                                    Opportunity_Source__c = 'Customer Referral',
                                                    Reference__c = '123');
        insert incorrectOpp2; 
        
        incorrectOpp2.CloseDate = lastWeek;
        update incorrectOpp2;
    }
    @isTest static void testOpportunityFail(){
        Boolean success = true;
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse(); 
        req.requestURI = '/services/apexrest/RecentlyWonOpportunities/';
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response= res;
        List<Opportunity> result = RecentlyWonOpportunities.doGet();
        
        for(integer i = 0; i < result.size(); i++){
            if(result[i].Name == 'TestingFalse'){
                success = false;
            }
        } 
        system.assert(success);
    }
    @isTest static void testOpportunitySuccess(){
        Boolean success = false;
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse(); 
        req.requestURI = '/services/apexrest/RecentlyWonOpportunities/';
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response= res;
        List<Opportunity> result = RecentlyWonOpportunities.doGet();

        for(integer i = 0; i < result.size(); i++){  
            if(result[i].Name == 'TestingTrue'){
                success = true;
            }
        } 
		system.assert(success);
    }

}